# Generated by Django 5.0.1 on 2024-01-26 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюдо',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('amount_used', models.PositiveIntegerField(default=0, null=True, verbose_name='Использованно')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='DishRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gram_weight', models.PositiveIntegerField(verbose_name='Вес в граммах')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.dish', verbose_name='Блюдо')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.ingredient', verbose_name='Ингридиент')),
            ],
            options={
                'verbose_name': 'Рецепт блюда',
                'verbose_name_plural': 'Рецепты блюд',
            },
        ),
        migrations.AddConstraint(
            model_name='dishrecipe',
            constraint=models.UniqueConstraint(fields=('dish', 'ingredient'), name='unique_ingredient_for_dish'),
        ),
    ]
